USE [master]
GO
/****** Object:  Database [report]    Script Date: 2023/4/3 下午 12:01:04 ******/
CREATE DATABASE [report]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'test03', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\test03.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'test03_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\test03_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [report] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [report].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [report] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [report] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [report] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [report] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [report] SET ARITHABORT OFF 
GO
ALTER DATABASE [report] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [report] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [report] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [report] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [report] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [report] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [report] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [report] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [report] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [report] SET  DISABLE_BROKER 
GO
ALTER DATABASE [report] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [report] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [report] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [report] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [report] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [report] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [report] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [report] SET RECOVERY FULL 
GO
ALTER DATABASE [report] SET  MULTI_USER 
GO
ALTER DATABASE [report] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [report] SET DB_CHAINING OFF 
GO
ALTER DATABASE [report] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [report] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [report] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [report] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'report', N'ON'
GO
ALTER DATABASE [report] SET QUERY_STORE = OFF
GO
USE [report]
GO
/****** Object:  Table [dbo].[reports]    Script Date: 2023/4/3 下午 12:01:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[reports](
	[reportNo] [int] IDENTITY(1,1) NOT NULL,
	[ID] [int] NOT NULL,
	[reportedID] [int] NOT NULL,
	[reportTime] [datetime] NOT NULL,
	[reportType] [nvarchar](20) NOT NULL,
	[reportReason] [nvarchar](200) NOT NULL,
	[status] [int] NULL,
	[reply] [nvarchar](500) NULL,
 CONSTRAINT [PK_reports] PRIMARY KEY CLUSTERED 
(
	[reportNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[reports] ADD  CONSTRAINT [DF_reports_status]  DEFAULT ((0)) FOR [status]
GO
USE [master]
GO
ALTER DATABASE [report] SET  READ_WRITE 
GO
